jQuery(function($) { 
  $(document).ready( function() { 

    var $sidenav = $("#affix-nav")
    var $body = $("body");
    var body_pandding_top = $body.css("padding-top");
    var $head_refer;
    var $caption_refer;
    var head_refer_pandding_top;
    var head_refer_margin_top;
    var caption_refer_pandding_top;
    var caption_refer_margin_top;

    function init_refer()
    {
        head_refer_pandding_top = $("h2[id]").css("padding-top");
        head_refer_margin_top = $("h2[id]").css("margin-top");
        caption_refer_pandding_top = $("caption[id]").css("padding-top");
        caption_refer_margin_top = $("caption[id]").css("margin-top");

        $head_refer = $("h1[id], h2[id], h3[id], h4[id], h5[id], h6[id]");
        $caption_refer = $("h1[id]:first-child, caption[id], .caption[id], .figure[id], .footnoteRef[id]");
        console.log($head_refer);
        console.log($caption_refer);
    }

 
    //Generated table of content
    function generate_toc()
    {
      $sidenav.toc();
      var navWidth = $sidenav.width();
      $(".sidenav").width(navWidth);
    }


    //Assume that the caption of figure is 'figure1 ba la ba la ba la'
    //This function will return the first world figure1
    function make_figure_id(caption)
    {
      var worlds = caption.split(' ', 1);
      if(worlds.length)
        return worlds[0];
      else
        return "";
    }
    
    //Update figure title for generated by R
    function update_figure_titile(caption_is_above_figure)
    {
      var $caps =  $('.caption');

      $caps.each(function(idx, cap){
        var $cap = $(cap);
        var id = make_figure_id($cap.html());
        if (caption_is_above_figure)
        {
          $cap.addClass('caption-above')
              .attr('id', id);

          /*Move The Title To Above The Figure*/
          var $img = $cap.prev("img");
          if($img.length)
            $img.addClass('img-below')
                .before(cap);
        }
        else
        {
          var $parent = $cap.parent();
          $parent.attr('id', id);
        }
      });
    }

    //Update table title for generated by R
    function update_table_titile()
    {
      var $caps =  $('caption');

      $caps.each(function(idx, cap){
        var $cap = $(cap);
        var id = make_figure_id($cap.html());
        $cap.attr('id', id);
      });
    }

    function init_dock()
    {
      var $full_screen = $("#full_screen");
      var $window = $(window);
      var $dock = $("#dock");

      function update_dock_position()
      {
        var $doc_content = $("#doc_content");
        
        var dock_right = $window.width() - ($doc_content.outerWidth() + 
                                          $doc_content.position().left +
                                          $dock.outerWidth());

        $dock.css({"right": dock_right + "px"});
      }

      function full_screnn_listener() 
      {
        var scroll_top = $window.scrollTop();
 
       if($full_screen.hasClass("glyphicon-resize-small"))
        {
          $(".navbar").show();
          $sidenav.show();
          $("#doc_content").attr('class', 'col-lg-9');
          //$body.css({"padding-top": body_pandding_top});
          //$head_refer.css({"padding-top": head_refer_pandding_top, "margin-top": head_refer_margin_top});
          //$caption_refer.css({"padding-top": caption_refer_pandding_top, "margin-top": caption_refer_margin_top});
          //$window.scrollTop(scroll_top - 10);
        }
        else
        {
          $(".navbar").hide();
          $sidenav.hide();
          $("#doc_content").attr('class', 'col-lg-12');
          //$body.css({"padding-top": "0px"});
          //$head_refer.css({"padding-top": "0px", "margin-top": "0px"});
          //$caption_refer.css({"padding-top": "0px", "margin-top": "0px"});
          //$window.scrollTop(scroll_top + 10);
        }
        $full_screen.toggleClass("glyphicon-resize-small");

        return false;
      }

      function update_go_to_top()
      {
        var height = $window.height();
        var $go_to_top = $("#go_to_top");
        if($window.scrollTop() > height)
          $go_to_top.show();
        else
          $go_to_top.hide();
      }

      $full_screen.click(full_screnn_listener);

      $window.resize(update_dock_position)
             .scroll(update_go_to_top);

      update_dock_position();
      update_go_to_top();
      $dock.show();
    }

    generate_toc();
    update_figure_titile();
    update_table_titile();
    init_refer();
    init_dock();
  }); 
}); 
